from langchain_core.prompts import ChatPromptTemplate

"""
This module provides an experimental summarization script using a state graph to process and summarize large documents.
No useful data has been generated yet, but it could be a crucial way to enhance the large context Retrieval-Augmented Generation (RAG).

Classes:
    OverallState: A TypedDict representing the overall state of the main graph, including input document contents, summaries, collapsed summaries, and a final summary.
    SummaryState: A TypedDict representing the state of a node used to generate summaries from documents.

Functions:
    length_function(documents: List[Document]) -> int:
        Calculates the number of tokens for input contents.
    
        Generates a summary given a document.
    
        Maps out over the documents to generate summaries.
    
        Collects summaries into collapsed summaries.
    
        Reduces a set of summaries into a final, consolidated summary.
    
        Collapses summaries if the number of tokens exceeds the maximum token limit.
    
    def should_collapse(state: OverallState) -> Literal["collapse_summaries", "generate_final_summary"]:
        Determines if summaries should be collapsed based on the number of tokens.
    
        Generates the final summary from collapsed summaries.
    
        Processes the steps in the state graph asynchronously.

Note:
    This summarization script is still under experimental development. No useful data has been generated yet, but it could be a crucial way to enhance the large context Retrieval-Augmented Generation (RAG).
"""

from langchain import hub

map_prompt = hub.pull("rlm/map-prompt")
reduce_template = """
The following is a set of summaries:
{docs}
Take these and distill it into a final, consolidated summary
of the main themes.
"""
from langchain_ollama import ChatOllama
llm = ChatOllama(
    base_url="http://localhost:11434",
    model="llama3.2:3b-instruct-q8_0"
)

reduce_prompt = ChatPromptTemplate([("human", reduce_template)])
import operator
from typing import Annotated, List, Literal, TypedDict

from langchain.chains.combine_documents.reduce import (
    acollapse_docs,
    split_list_of_docs,
)
from langchain_core.documents import Document
from langgraph.constants import Send
from langgraph.graph import END, START, StateGraph

token_max = 1000


def length_function(documents: List[Document]) -> int:
    """Get number of tokens for input contents."""
    return sum(llm.get_num_tokens(doc.page_content) for doc in documents)


# This will be the overall state of the main graph.
# It will contain the input document contents, corresponding
# summaries, and a final summary.
class OverallState(TypedDict):
    # Notice here we use the operator.add
    # This is because we want combine all the summaries we generate
    # from individual nodes back into one list - this is essentially
    # the "reduce" part
    contents: List[str]
    summaries: Annotated[list, operator.add]
    collapsed_summaries: List[Document]
    final_summary: str


# This will be the state of the node that we will "map" all
# documents to in order to generate summaries
class SummaryState(TypedDict):
    content: str


# Here we generate a summary, given a document
async def generate_summary(state: SummaryState):
    prompt = map_prompt.invoke(state["content"])
    response = await llm.ainvoke(prompt)
    return {"summaries": [response.content]}


# Here we define the logic to map out over the documents
# We will use this an edge in the graph
def map_summaries(state: OverallState):
    # We will return a list of `Send` objects
    # Each `Send` object consists of the name of a node in the graph
    # as well as the state to send to that node
    return [
        Send("generate_summary", {"content": content}) for content in state["contents"]
    ]


def collect_summaries(state: OverallState):
    return {
        "collapsed_summaries": [Document(summary) for summary in state["summaries"]]
    }


async def _reduce(input: dict) -> str:
    prompt = reduce_prompt.invoke(input)
    response = await llm.ainvoke(prompt)
    return response.content


# Add node to collapse summaries
async def collapse_summaries(state: OverallState):
    doc_lists = split_list_of_docs(
        state["collapsed_summaries"], length_function, token_max
    )
    results = []
    for doc_list in doc_lists:
        results.append(await acollapse_docs(doc_list, _reduce))

    return {"collapsed_summaries": results}


# This represents a conditional edge in the graph that determines
# if we should collapse the summaries or not
def should_collapse(
    state: OverallState,
) -> Literal["collapse_summaries", "generate_final_summary"]:
    num_tokens = length_function(state["collapsed_summaries"])
    if num_tokens > token_max:
        return "collapse_summaries"
    else:
        return "generate_final_summary"


# Here we will generate the final summary
async def generate_final_summary(state: OverallState):
    response = await _reduce(state["collapsed_summaries"])
    return {"final_summary": response}


# Construct the graph
# Nodes:
graph = StateGraph(OverallState)
graph.add_node("generate_summary", generate_summary)  # same as before
graph.add_node("collect_summaries", collect_summaries)
graph.add_node("collapse_summaries", collapse_summaries)
graph.add_node("generate_final_summary", generate_final_summary)

# Edges:
graph.add_conditional_edges(START, map_summaries, ["generate_summary"])
graph.add_edge("generate_summary", "collect_summaries")
graph.add_conditional_edges("collect_summaries", should_collapse)
graph.add_conditional_edges("collapse_summaries", should_collapse)
graph.add_edge("generate_final_summary", END)

app = graph.compile()

from IPython.display import Image

try:
    image = Image(app.get_graph().draw_mermaid_png())
    with open("logs/summary_graph.png", "wb") as f:
        f.write(image.data)
    print("Graph saved as graph.png")
except Exception as e:
    print(f"An error occurred: {e}")


split_docs = [
    "What I Worked On \n \nFebruary 2021 \n \nBefore college the two main things I worked on, outside of school, were writing and programming. I \ndidn't write essays. I wrote what beginning writers were supposed to write then, and probably still are: \nshort stories. My stories were awful. They had hardly any plot, just characters with strong feelings, \nwhich I imagined made them deep. \n \nThe first programs I tried writing were on the IBM 1401 that our school district used for what was then \ncalled \"data processing.\" This was in 9th grade, so I was 13 or 14. The school district's 1401 happened to \nbe in the basement of our junior high school, and my friend Rich Draves and I got permission to use it. It \nwas like a mini Bond villain's lair down there, with all these alien-looking machines — CPU, disk drives, \nprinter, card reader — sitting up on a raised floor under bright fluorescent lights. \n \nThe language we used was an early version of Fortran. You had to type programs on punch cards, then \nstack them in the card reader and press a button to load the program into memory and run it. The result \nwould ordinarily be to print something on the spectacularly loud printer. \n \nI was puzzled by the 1401. I couldn't figure out what to do with it. And in retrospect there's not much I \ncould have done with it. The only form of input to programs was data stored on punched cards, and I \ndidn't have any data stored on punched cards. The only other option was to do things that didn't rely on \nany input, like calculate approximations of pi, but I didn't know enough math to do anything interesting \nof that type. So I'm not surprised I can't remember any programs I wrote, because they can't have done \nmuch. My clearest memory is of the moment I learned it was possible for programs not to terminate, \nwhen one of mine didn't. On a machine without time-sharing, this was a social as well as a technical \nerror, as the data center manager's expression made clear.",
    "error, as the data center manager's expression made clear. \n \nWith microcomputers, everything changed. Now you could have a computer sitting right in front of you, \non a desk, that could respond to your keystrokes as it was running instead of just churning through a \nstack of punch cards and then stopping. [1] \n \nThe first of my friends to get a microcomputer built it himself. It was sold as a kit by Heathkit. I \nremember vividly how impressed and envious I felt watching him sitting in front of it, typing programs \nright into the computer.",
    "Computers were expensive in those days and it took me years of nagging before I convinced my father \nto buy one, a TRS-80, in about 1980. The gold standard then was the Apple II, but a TRS-80 was good \nenough. This was when I really started programming. I wrote simple games, a program to predict how \nhigh my model rockets would fly, and a word processor that my father used to write at least one book. \nThere was only room in memory for about 2 pages of text, so he'd write 2 pages at a time and then print \nthem out, but it was a lot better than a typewriter. \n \nThough I liked programming, I didn't plan to study it in college. In college I was going to study \nphilosophy, which sounded much more powerful. It seemed, to my naive high school self, to be the \nstudy of the ultimate truths, compared to which the things studied in other fields would be mere \ndomain knowledge. What I discovered when I got to college was that the other fields took up so much of \nthe space of ideas that there wasn't much left for these supposed ultimate truths. All that seemed left \nfor philosophy were edge cases that people in other fields felt could safely be ignored. \n \nI couldn't have put this into words when I was 18. All I knew at the time was that I kept taking \nphilosophy courses and they kept being boring. So I decided to switch to AI. \n \nAI was in the air in the mid 1980s, but there were two things especially that made me want to work on \nit: a novel by Heinlein called The Moon is a Harsh Mistress, which featured an intelligent computer \ncalled Mike, and a PBS documentary that showed Terry Winograd using SHRDLU. I haven't tried \nrereading The Moon is a Harsh Mistress, so I don't know how well it has aged, but when I read it I was \ndrawn entirely into its world. It seemed only a matter of time before we'd have Mike, and when I saw \nWinograd using SHRDLU, it seemed like that time would be a few years at most. All you had to do was \nteach SHRDLU more words.",
    "teach SHRDLU more words. \n \nThere weren't any classes in AI at Cornell then, not even graduate classes, so I started trying to teach \nmyself. Which meant learning Lisp, since in those days Lisp was regarded as the language of AI. The \ncommonly used programming languages then were pretty primitive, and programmers' ideas \ncorrespondingly so. The default language at Cornell was a Pascal-like language called PL/I, and the \nsituation was similar elsewhere. Learning Lisp expanded my concept of a program so fast that it was \nyears before I started to have a sense of where the new limits were. This was more like it; this was what \nI had expected college to do. It wasn't happening in a class, like it was supposed to, but that was ok. For \nthe next couple years I was on a roll. I knew what I was going to do. \n \nFor my undergraduate thesis, I reverse-engineered SHRDLU. My God did I love working on that program. \nIt was a pleasing bit of code, but what made it even more exciting was my belief — hard to imagine now, \nbut not unique in 1985 — that it was already climbing the lower slopes of intelligence.",
    "I had gotten into a program at Cornell that didn't make you choose a major. You could take whatever \nclasses you liked, and choose whatever you liked to put on your degree. I of course chose \"Artificial \nIntelligence.\" When I got the actual physical diploma, I was dismayed to find that the quotes had been \nincluded, which made them read as scare-quotes. At the time this bothered me, but now it seems \namusingly accurate, for reasons I was about to discover. \n \nI applied to 3 grad schools: MIT and Yale, which were renowned for AI at the time, and Harvard, which \nI'd visited because Rich Draves went there, and was also home to Bill Woods, who'd invented the type of \nparser I used in my SHRDLU clone. Only Harvard accepted me, so that was where I went. \n \nI don't remember the moment it happened, or if there even was a specific moment, but during the first \nyear of grad school I realized that AI, as practiced at the time, was a hoax. By which I mean the sort of AI \nin which a program that's told \"the dog is sitting on the chair\" translates this into some formal \nrepresentation and adds it to the list of things it knows. \n \nWhat these programs really showed was that there's a subset of natural language that's a formal \nlanguage. But a very proper subset. It was clear that there was an unbridgeable gap between what they \ncould do and actually understanding natural language. It was not, in fact, simply a matter of teaching \nSHRDLU more words. That whole way of doing AI, with explicit data structures representing concepts, \nwas not going to work. Its brokenness did, as so often happens, generate a lot of opportunities to write \npapers about various band-aids that could be applied to it, but it was never going to get us Mike. \n \nSo I looked around to see what I could salvage from the wreckage of my plans, and there was Lisp. I \nknew from experience that Lisp was interesting for its own sake and not just for its association with AI,",
    "even though that was the main reason people cared about it at the time. So I decided to focus on Lisp. In \nfact, I decided to write a book about Lisp hacking. It's scary to think how little I knew about Lisp hacking \nwhen I started writing that book. But there's nothing like writing a book about something to help you \nlearn it. The book, On Lisp, wasn't published till 1993, but I wrote much of it in grad school. \n \nComputer Science is an uneasy alliance between two halves, theory and systems. The theory people \nprove things, and the systems people build things. I wanted to build things. I had plenty of respect for \ntheory — indeed, a sneaking suspicion that it was the more admirable of the two halves — but building \nthings seemed so much more exciting. \n \nThe problem with systems work, though, was that it didn't last. Any program you wrote today, no \nmatter how good, would be obsolete in a couple decades at best. People might mention your software \nin footnotes, but no one would actually use it. And indeed, it would seem very feeble work. Only people \nwith a sense of the history of the field would even realize that, in its time, it had been good.",
    "There were some surplus Xerox Dandelions floating around the computer lab at one point. Anyone who \nwanted one to play around with could have one. I was briefly tempted, but they were so slow by present \nstandards; what was the point? No one else wanted one either, so off they went. That was what \nhappened to systems work. \n \nI wanted not just to build things, but to build things that would last. \n \nIn this dissatisfied state I went in 1988 to visit Rich Draves at CMU, where he was in grad school. One \nday I went to visit the Carnegie Institute, where I'd spent a lot of time as a kid. While looking at a \npainting there I realized something that might seem obvious, but was a big surprise to me. There, right \non the wall, was something you could make that would last. Paintings didn't become obsolete. Some of \nthe best ones were hundreds of years old. \n \nAnd moreover this was something you could make a living doing. Not as easily as you could by writing \nsoftware, of course, but I thought if you were really industrious and lived really cheaply, it had to be \npossible to make enough to survive. And as an artist you could be truly independent. You wouldn't have \na boss, or even need to get research funding. \n \nI had always liked looking at paintings. Could I make them? I had no idea. I'd never imagined it was even \npossible. I knew intellectually that people made art — that it didn't just appear spontaneously — but it \nwas as if the people who made it were a different species. They either lived long ago or were mysterious \ngeniuses doing strange things in profiles in Life magazine. The idea of actually being able to make art, to \nput that verb before that noun, seemed almost miraculous. \n \nThat fall I started taking art classes at Harvard. Grad students could take classes in any department, and \nmy advisor, Tom Cheatham, was very easy going. If he even knew about the strange classes I was taking, \nhe never said anything.",
    "he never said anything. \n \nSo now I was in a PhD program in computer science, yet planning to be an artist, yet also genuinely in \nlove with Lisp hacking and working away at On Lisp. In other words, like many a grad student, I was \nworking energetically on multiple projects that were not my thesis. \n \nI didn't see a way out of this situation. I didn't want to drop out of grad school, but how else was I going \nto get out? I remember when my friend Robert Morris got kicked out of Cornell for writing the internet \nworm of 1988, I was envious that he'd found such a spectacular way to get out of grad school.",
    "Then one day in April 1990 a crack appeared in the wall. I ran into professor Cheatham and he asked if I \nwas far enough along to graduate that June. I didn't have a word of my dissertation written, but in what \nmust have been the quickest bit of thinking in my life, I decided to take a shot at writing one in the 5 \nweeks or so that remained before the deadline, reusing parts of On Lisp where I could, and I was able to \nrespond, with no perceptible delay \"Yes, I think so. I'll give you something to read in a few days.\" \n \nI picked applications of continuations as the topic. In retrospect I should have written about macros and \nembedded languages. There's a whole world there that's barely been explored. But all I wanted was to \nget out of grad school, and my rapidly written dissertation sufficed, just barely. \n \nMeanwhile I was applying to art schools. I applied to two: RISD in the US, and the Accademia di Belli Arti \nin Florence, which, because it was the oldest art school, I imagined would be good. RISD accepted me, \nand I never heard back from the Accademia, so off to Providence I went. \n \nI'd applied for the BFA program at RISD, which meant in effect that I had to go to college again. This was \nnot as strange as it sounds, because I was only 25, and art schools are full of people of different ages. \nRISD counted me as a transfer sophomore and said I had to do the foundation that summer. The \nfoundation means the classes that everyone has to take in fundamental subjects like drawing, color, and \ndesign. \n \nToward the end of the summer I got a big surprise: a letter from the Accademia, which had been \ndelayed because they'd sent it to Cambridge England instead of Cambridge Massachusetts, inviting me \nto take the entrance exam in Florence that fall. This was now only weeks away. My nice landlady let me \nleave my stuff in her attic. I had some money saved from consulting work I'd done in grad school; there",
    "was probably enough to last a year if I lived cheaply. Now all I had to do was learn Italian. \n \nOnly stranieri (foreigners) had to take this entrance exam. In retrospect it may well have been a way of \nexcluding them, because there were so many stranieri attracted by the idea of studying art in Florence \nthat the Italian students would otherwise have been outnumbered. I was in decent shape at painting \nand drawing from the RISD foundation that summer, but I still don't know how I managed to pass the \nwritten exam. I remember that I answered the essay question by writing about Cezanne, and that I \ncranked up the intellectual level as high as I could to make the most of my limited vocabulary. [2] \n \nI'm only up to age 25 and already there are such conspicuous patterns. Here I was, yet again about to \nattend some august institution in the hopes of learning about some prestigious subject, and yet again \nabout to be disappointed. The students and faculty in the painting department at the Accademia were",
    "the nicest people you could imagine, but they had long since arrived at an arrangement whereby the \nstudents wouldn't require the faculty to teach anything, and in return the faculty wouldn't require the \nstudents to learn anything. And at the same time all involved would adhere outwardly to the \nconventions of a 19th century atelier. We actually had one of those little stoves, fed with kindling, that \nyou see in 19th century studio paintings, and a nude model sitting as close to it as possible without \ngetting burned. Except hardly anyone else painted her besides me. The rest of the students spent their \ntime chatting or occasionally trying to imitate things they'd seen in American art magazines. \n \nOur model turned out to live just down the street from me. She made a living from a combination of \nmodelling and making fakes for a local antique dealer. She'd copy an obscure old painting out of a book, \nand then he'd take the copy and maltreat it to make it look old. [3] \n \nWhile I was a student at the Accademia I started painting still lives in my bedroom at night. These \npaintings were tiny, because the room was, and because I painted them on leftover scraps of canvas, \nwhich was all I could afford at the time. Painting still lives is different from painting people, because the \nsubject, as its name suggests, can't move. People can't sit for more than about 15 minutes at a time, and \nwhen they do they don't sit very still. So the traditional m.o. for painting people is to know how to paint \na generic person, which you then modify to match the specific person you're painting. Whereas a still \nlife you can, if you want, copy pixel by pixel from what you're seeing. You don't want to stop there, of \ncourse, or you get merely photographic accuracy, and what makes a still life interesting is that it's been \nthrough a head. You want to emphasize the visual cues that tell you, for example, that the reason the",
    "color changes suddenly at a certain point is that it's the edge of an object. By subtly emphasizing such \nthings you can make paintings that are more realistic than photographs not just in some metaphorical \nsense, but in the strict information-theoretic sense. [4] \n \nI liked painting still lives because I was curious about what I was seeing. In everyday life, we aren't \nconsciously aware of much we're seeing. Most visual perception is handled by low-level processes that \nmerely tell your brain \"that's a water droplet\" without telling you details like where the lightest and \ndarkest points are, or \"that's a bush\" without telling you the shape and position of every leaf. This is a \nfeature of brains, not a bug. In everyday life it would be distracting to notice every leaf on every bush. \nBut when you have to paint something, you have to look more closely, and when you do there's a lot to \nsee. You can still be noticing new things after days of trying to paint something people usually take for \ngranted, just as you can after days of trying to write an essay about something people usually take for \ngranted. \n \nThis is not the only way to paint. I'm not 100% sure it's even a good way to paint. But it seemed a good \nenough bet to be worth trying.",
    "Our teacher, professor Ulivi, was a nice guy. He could see I worked hard, and gave me a good grade, \nwhich he wrote down in a sort of passport each student had. But the Accademia wasn't teaching me \nanything except Italian, and my money was running out, so at the end of the first year I went back to the \nUS. \n \nI wanted to go back to RISD, but I was now broke and RISD was very expensive, so I decided to get a job \nfor a year and then return to RISD the next fall. I got one at a company called Interleaf, which made \nsoftware for creating documents. You mean like Microsoft Word? Exactly. That was how I learned that \nlow end software tends to eat high end software. But Interleaf still had a few years to live yet. [5] \n \nInterleaf had done something pretty bold. Inspired by Emacs, they'd added a scripting language, and \neven made the scripting language a dialect of Lisp. Now they wanted a Lisp hacker to write things in it. \nThis was the closest thing I've had to a normal job, and I hereby apologize to my boss and coworkers, \nbecause I was a bad employee. Their Lisp was the thinnest icing on a giant C cake, and since I didn't \nknow C and didn't want to learn it, I never understood most of the software. Plus I was terribly \nirresponsible. This was back when a programming job meant showing up every day during certain \nworking hours. That seemed unnatural to me, and on this point the rest of the world is coming around \nto my way of thinking, but at the time it caused a lot of friction. Toward the end of the year I spent much \nof my time surreptitiously working on On Lisp, which I had by this time gotten a contract to publish. \n \nThe good part was that I got paid huge amounts of money, especially by art student standards. In \nFlorence, after paying my part of the rent, my budget for everything else had been $7 a day. Now I was \ngetting paid more than 4 times that every hour, even when I was just sitting in a meeting. By living",
    "cheaply I not only managed to save enough to go back to RISD, but also paid off my college loans. \n \nI learned some useful things at Interleaf, though they were mostly about what not to do. I learned that \nit's better for technology companies to be run by product people than sales people (though sales is a \nreal skill and people who are good at it are really good at it), that it leads to bugs when code is edited by \ntoo many people, that cheap office space is no bargain if it's depressing, that planned meetings are \ninferior to corridor conversations, that big, bureaucratic customers are a dangerous source of money, \nand that there's not much overlap between conventional office hours and the optimal time for hacking, \nor conventional offices and the optimal place for it. \n \nBut the most important thing I learned, and which I used in both Viaweb and Y Combinator, is that the \nlow end eats the high end: that it's good to be the \"entry level\" option, even though that will be less \nprestigious, because if you're not, someone else will be, and will squash you against the ceiling. Which in \nturn means that prestige is a danger sign.",
    "When I left to go back to RISD the next fall, I arranged to do freelance work for the group that did \nprojects for customers, and this was how I survived for the next several years. When I came back to visit \nfor a project later on, someone told me about a new thing called HTML, which was, as he described it, a \nderivative of SGML. Markup language enthusiasts were an occupational hazard at Interleaf and I ignored \nhim, but this HTML thing later became a big part of my life. \n \nIn the fall of 1992 I moved back to Providence to continue at RISD. The foundation had merely been \nintro stuff, and the Accademia had been a (very civilized) joke. Now I was going to see what real art \nschool was like. But alas it was more like the Accademia than not. Better organized, certainly, and a lot \nmore expensive, but it was now becoming clear that art school did not bear the same relationship to art \nthat medical school bore to medicine. At least not the painting department. The textile department, \nwhich my next door neighbor belonged to, seemed to be pretty rigorous. No doubt illustration and \narchitecture were too. But painting was post-rigorous. Painting students were supposed to express \nthemselves, which to the more worldly ones meant to try to cook up some sort of distinctive signature \nstyle. \n \nA signature style is the visual equivalent of what in show business is known as a \"schtick\": something \nthat immediately identifies the work as yours and no one else's. For example, when you see a painting \nthat looks like a certain kind of cartoon, you know it's by Roy Lichtenstein. So if you see a big painting of \nthis type hanging in the apartment of a hedge fund manager, you know he paid millions of dollars for it. \nThat's not always why artists have a signature style, but it's usually why buyers pay a lot for such work. \n[6] \n \nThere were plenty of earnest students too: kids who \"could draw\" in high school, and now had come to",
    "what was supposed to be the best art school in the country, to learn to draw even better. They tended \nto be confused and demoralized by what they found at RISD, but they kept going, because painting was \nwhat they did. I was not one of the kids who could draw in high school, but at RISD I was definitely closer \nto their tribe than the tribe of signature style seekers. \n \nI learned a lot in the color class I took at RISD, but otherwise I was basically teaching myself to paint, and \nI could do that for free. So in 1993 I dropped out. I hung around Providence for a bit, and then my \ncollege friend Nancy Parmet did me a big favor. A rent-controlled apartment in a building her mother \nowned in New York was becoming vacant. Did I want it? It wasn't much more than my current place, and \nNew York was supposed to be where the artists were. So yes, I wanted it! [7] \n \nAsterix comics begin by zooming in on a tiny corner of Roman Gaul that turns out not to be controlled by \nthe Romans. You can do something similar on a map of New York City: if you zoom in on the Upper East \nSide, there's a tiny corner that's not rich, or at least wasn't in 1993. It's called Yorkville, and that was my",
    "new home. Now I was a New York artist — in the strictly technical sense of making paintings and living in \nNew York. \n \nI was nervous about money, because I could sense that Interleaf was on the way down. Freelance Lisp \nhacking work was very rare, and I didn't want to have to program in another language, which in those \ndays would have meant C++ if I was lucky. So with my unerring nose for financial opportunity, I decided \nto write another book on Lisp. This would be a popular book, the sort of book that could be used as a \ntextbook. I imagined myself living frugally off the royalties and spending all my time painting. (The \npainting on the cover of this book, ANSI Common Lisp, is one that I painted around this time.) \n \nThe best thing about New York for me was the presence of Idelle and Julian Weber. Idelle Weber was a \npainter, one of the early photorealists, and I'd taken her painting class at Harvard. I've never known a \nteacher more beloved by her students. Large numbers of former students kept in touch with her, \nincluding me. After I moved to New York I became her de facto studio assistant. \n \nShe liked to paint on big, square canvases, 4 to 5 feet on a side. One day in late 1994 as I was stretching \none of these monsters there was something on the radio about a famous fund manager. He wasn't that \nmuch older than me, and was super rich. The thought suddenly occurred to me: why don't I become \nrich? Then I'll be able to work on whatever I want. \n \nMeanwhile I'd been hearing more and more about this new thing called the World Wide Web. Robert \nMorris showed it to me when I visited him in Cambridge, where he was now in grad school at Harvard. It \nseemed to me that the web would be a big deal. I'd seen what graphical user interfaces had done for the \npopularity of microcomputers. It seemed like the web would do the same for the internet. \n \nIf I wanted to get rich, here was the next train leaving the station. I was right about that part. What I got",
    "wrong was the idea. I decided we should start a company to put art galleries online. I can't honestly say, \nafter reading so many Y Combinator applications, that this was the worst startup idea ever, but it was up \nthere. Art galleries didn't want to be online, and still don't, not the fancy ones. That's not how they sell. I \nwrote some software to generate web sites for galleries, and Robert wrote some to resize images and \nset up an http server to serve the pages. Then we tried to sign up galleries. To call this a difficult sale \nwould be an understatement. It was difficult to give away. A few galleries let us make sites for them for \nfree, but none paid us. \n \nThen some online stores started to appear, and I realized that except for the order buttons they were \nidentical to the sites we'd been generating for galleries. This impressive-sounding thing called an \n\"internet storefront\" was something we already knew how to build.",
    "So in the summer of 1995, after I submitted the camera-ready copy of ANSI Common Lisp to the \npublishers, we started trying to write software to build online stores. At first this was going to be normal \ndesktop software, which in those days meant Windows software. That was an alarming prospect, \nbecause neither of us knew how to write Windows software or wanted to learn. We lived in the Unix \nworld. But we decided we'd at least try writing a prototype store builder on Unix. Robert wrote a \nshopping cart, and I wrote a new site generator for stores — in Lisp, of course. \n \nWe were working out of Robert's apartment in Cambridge. His roommate was away for big chunks of \ntime, during which I got to sleep in his room. For some reason there was no bed frame or sheets, just a \nmattress on the floor. One morning as I was lying on this mattress I had an idea that made me sit up like \na capital L. What if we ran the software on the server, and let users control it by clicking on links? Then \nwe'd never have to write anything to run on users' computers. We could generate the sites on the same \nserver we'd serve them from. Users wouldn't need anything more than a browser. \n \nThis kind of software, known as a web app, is common now, but at the time it wasn't clear that it was \neven possible. To find out, we decided to try making a version of our store builder that you could control \nthrough the browser. A couple days later, on August 12, we had one that worked. The UI was horrible, \nbut it proved you could build a whole store through the browser, without any client software or typing \nanything into the command line on the server. \n \nNow we felt like we were really onto something. I had visions of a whole new generation of software \nworking this way. You wouldn't need versions, or ports, or any of that crap. At Interleaf there had been a \nwhole group called Release Engineering that seemed to be at least as big as the group that actually",
    "wrote the software. Now you could just update the software right on the server. \n \nWe started a new company we called Viaweb, after the fact that our software worked via the web, and \nwe got $10,000 in seed funding from Idelle's husband Julian. In return for that and doing the initial legal \nwork and giving us business advice, we gave him 10% of the company. Ten years later this deal became \nthe model for Y Combinator's. We knew founders needed something like this, because we'd needed it \nourselves. \n \nAt this stage I had a negative net worth, because the thousand dollars or so I had in the bank was more \nthan counterbalanced by what I owed the government in taxes. (Had I diligently set aside the proper \nproportion of the money I'd made consulting for Interleaf? No, I had not.) So although Robert had his \ngraduate student stipend, I needed that seed funding to live on.",
    "We originally hoped to launch in September, but we got more ambitious about the software as we \nworked on it. Eventually we managed to build a WYSIWYG site builder, in the sense that as you were \ncreating pages, they looked exactly like the static ones that would be generated later, except that \ninstead of leading to static pages, the links all referred to closures stored in a hash table on the server. \n \nIt helped to have studied art, because the main goal of an online store builder is to make users look \nlegit, and the key to looking legit is high production values. If you get page layouts and fonts and colors \nright, you can make a guy running a store out of his bedroom look more legit than a big company. \n \n(If you're curious why my site looks so old-fashioned, it's because it's still made with this software. It \nmay look clunky today, but in 1996 it was the last word in slick.) \n \nIn September, Robert rebelled. \"We've been working on this for a month,\" he said, \"and it's still not \ndone.\" This is funny in retrospect, because he would still be working on it almost 3 years later. But I \ndecided it might be prudent to recruit more programmers, and I asked Robert who else in grad school \nwith him was really good. He recommended Trevor Blackwell, which surprised me at first, because at \nthat point I knew Trevor mainly for his plan to reduce everything in his life to a stack of notecards, which \nhe carried around with him. But Rtm was right, as usual. Trevor turned out to be a frighteningly effective \nhacker. \n \nIt was a lot of fun working with Robert and Trevor. They're the two most independent-minded people I \nknow, and in completely different ways. If you could see inside Rtm's brain it would look like a colonial \nNew England church, and if you could see inside Trevor's it would look like the worst excesses of \nAustrian Rococo. \n \nWe opened for business, with 6 stores, in January 1996. It was just as well we waited a few months,",
    "because although we worried we were late, we were actually almost fatally early. There was a lot of talk \nin the press then about ecommerce, but not many people actually wanted online stores. [8] \n \nThere were three main parts to the software: the editor, which people used to build sites and which I \nwrote, the shopping cart, which Robert wrote, and the manager, which kept track of orders and \nstatistics, and which Trevor wrote. In its time, the editor was one of the best general-purpose site \nbuilders. I kept the code tight and didn't have to integrate with any other software except Robert's and \nTrevor's, so it was quite fun to work on. If all I'd had to do was work on this software, the next 3 years \nwould have been the easiest of my life. Unfortunately I had to do a lot more, all of it stuff I was worse at \nthan programming, and the next 3 years were instead the most stressful.",
    "There were a lot of startups making ecommerce software in the second half of the 90s. We were \ndetermined to be the Microsoft Word, not the Interleaf. Which meant being easy to use and \ninexpensive. It was lucky for us that we were poor, because that caused us to make Viaweb even more \ninexpensive than we realized. We charged $100 a month for a small store and $300 a month for a big \none. This low price was a big attraction, and a constant thorn in the sides of competitors, but it wasn't \nbecause of some clever insight that we set the price low. We had no idea what businesses paid for \nthings. $300 a month seemed like a lot of money to us. \n \nWe did a lot of things right by accident like that. For example, we did what's now called \"doing things \nthat don't scale,\" although at the time we would have described it as \"being so lame that we're driven to \nthe most desperate measures to get users.\" The most common of which was building stores for them. \nThis seemed particularly humiliating, since the whole raison d'etre of our software was that people \ncould use it to make their own stores. But anything to get users. \n \nWe learned a lot more about retail than we wanted to know. For example, that if you could only have a \nsmall image of a man's shirt (and all images were small then by present standards), it was better to have \na closeup of the collar than a picture of the whole shirt. The reason I remember learning this was that it \nmeant I had to rescan about 30 images of men's shirts. My first set of scans were so beautiful too. \n \nThough this felt wrong, it was exactly the right thing to be doing. Building stores for users taught us \nabout retail, and about how it felt to use our software. I was initially both mystified and repelled by \n\"business\" and thought we needed a \"business person\" to be in charge of it, but once we started to get \nusers, I was converted, in much the same way I was converted to fatherhood once I had kids. Whatever",
    "users wanted, I was all theirs. Maybe one day we'd have so many users that I couldn't scan their images \nfor them, but in the meantime there was nothing more important to do. \n \nAnother thing I didn't get at the time is that growth rate is the ultimate test of a startup. Our growth \nrate was fine. We had about 70 stores at the end of 1996 and about 500 at the end of 1997. I mistakenly \nthought the thing that mattered was the absolute number of users. And that is the thing that matters in \nthe sense that that's how much money you're making, and if you're not making enough, you might go \nout of business. But in the long term the growth rate takes care of the absolute number. If we'd been a \nstartup I was advising at Y Combinator, I would have said: Stop being so stressed out, because you're \ndoing fine. You're growing 7x a year. Just don't hire too many more people and you'll soon be profitable, \nand then you'll control your own destiny. \n \nAlas I hired lots more people, partly because our investors wanted me to, and partly because that's what \nstartups did during the Internet Bubble. A company with just a handful of employees would have \nseemed amateurish. So we didn't reach breakeven until about when Yahoo bought us in the summer of \n1998. Which in turn meant we were at the mercy of investors for the entire life of the company. And",
    "since both we and our investors were noobs at startups, the result was a mess even by startup \nstandards. \n \nIt was a huge relief when Yahoo bought us. In principle our Viaweb stock was valuable. It was a share in \na business that was profitable and growing rapidly. But it didn't feel very valuable to me; I had no idea \nhow to value a business, but I was all too keenly aware of the near-death experiences we seemed to \nhave every few months. Nor had I changed my grad student lifestyle significantly since we started. So \nwhen Yahoo bought us it felt like going from rags to riches. Since we were going to California, I bought a \ncar, a yellow 1998 VW GTI. I remember thinking that its leather seats alone were by far the most \nluxurious thing I owned. \n \nThe next year, from the summer of 1998 to the summer of 1999, must have been the least productive of \nmy life. I didn't realize it at the time, but I was worn out from the effort and stress of running Viaweb. \nFor a while after I got to California I tried to continue my usual m.o. of programming till 3 in the \nmorning, but fatigue combined with Yahoo's prematurely aged culture and grim cube farm in Santa \nClara gradually dragged me down. After a few months it felt disconcertingly like working at Interleaf. \n \nYahoo had given us a lot of options when they bought us. At the time I thought Yahoo was so overvalued \nthat they'd never be worth anything, but to my astonishment the stock went up 5x in the next year. I \nhung on till the first chunk of options vested, then in the summer of 1999 I left. It had been so long since \nI'd painted anything that I'd half forgotten why I was doing this. My brain had been entirely full of \nsoftware and men's shirts for 4 years. But I had done this to get rich so I could paint, I reminded myself, \nand now I was rich, so I should go paint. \n \nWhen I said I was leaving, my boss at Yahoo had a long conversation with me about my plans. I told him",
    "all about the kinds of pictures I wanted to paint. At the time I was touched that he took such an interest \nin me. Now I realize it was because he thought I was lying. My options at that point were worth about $2 \nmillion a month. If I was leaving that kind of money on the table, it could only be to go and start some \nnew startup, and if I did, I might take people with me. This was the height of the Internet Bubble, and \nYahoo was ground zero of it. My boss was at that moment a billionaire. Leaving then to start a new \nstartup must have seemed to him an insanely, and yet also plausibly, ambitious plan. \n \nBut I really was quitting to paint, and I started immediately. There was no time to lose. I'd already \nburned 4 years getting rich. Now when I talk to founders who are leaving after selling their companies, \nmy advice is always the same: take a vacation. That's what I should have done, just gone off somewhere \nand done nothing for a month or two, but the idea never occurred to me.",
    "So I tried to paint, but I just didn't seem to have any energy or ambition. Part of the problem was that I \ndidn't know many people in California. I'd compounded this problem by buying a house up in the Santa \nCruz Mountains, with a beautiful view but miles from anywhere. I stuck it out for a few more months, \nthen in desperation I went back to New York, where unless you understand about rent control you'll be \nsurprised to hear I still had my apartment, sealed up like a tomb of my old life. Idelle was in New York at \nleast, and there were other people trying to paint there, even though I didn't know any of them. \n \nWhen I got back to New York I resumed my old life, except now I was rich. It was as weird as it sounds. I \nresumed all my old patterns, except now there were doors where there hadn't been. Now when I was \ntired of walking, all I had to do was raise my hand, and (unless it was raining) a taxi would stop to pick \nme up. Now when I walked past charming little restaurants I could go in and order lunch. It was exciting \nfor a while. Painting started to go better. I experimented with a new kind of still life where I'd paint one \npainting in the old way, then photograph it and print it, blown up, on canvas, and then use that as the \nunderpainting for a second still life, painted from the same objects (which hopefully hadn't rotted yet). \n \nMeanwhile I looked for an apartment to buy. Now I could actually choose what neighborhood to live in. \nWhere, I asked myself and various real estate agents, is the Cambridge of New York? Aided by \noccasional visits to actual Cambridge, I gradually realized there wasn't one. Huh. \n \nAround this time, in the spring of 2000, I had an idea. It was clear from our experience with Viaweb that \nweb apps were the future. Why not build a web app for making web apps? Why not let people edit code \non our server through the browser, and then host the resulting applications for them? [9] You could run",
    "all sorts of services on the servers that these applications could use just by making an API call: making \nand receiving phone calls, manipulating images, taking credit card payments, etc. \n \nI got so excited about this idea that I couldn't think about anything else. It seemed obvious that this was \nthe future. I didn't particularly want to start another company, but it was clear that this idea would have \nto be embodied as one, so I decided to move to Cambridge and start it. I hoped to lure Robert into \nworking on it with me, but there I ran into a hitch. Robert was now a postdoc at MIT, and though he'd \nmade a lot of money the last time I'd lured him into working on one of my schemes, it had also been a \nhuge time sink. So while he agreed that it sounded like a plausible idea, he firmly refused to work on it. \n \nHmph. Well, I'd do it myself then. I recruited Dan Giffin, who had worked for Viaweb, and two \nundergrads who wanted summer jobs, and we got to work trying to build what it's now clear is about \ntwenty companies and several open source projects worth of software. The language for defining \napplications would of course be a dialect of Lisp. But I wasn't so naive as to assume I could spring an \novert Lisp on a general audience; we'd hide the parentheses, like Dylan did.",
    "By then there was a name for the kind of company Viaweb was, an \"application service provider,\" or \nASP. This name didn't last long before it was replaced by \"software as a service,\" but it was current for \nlong enough that I named this new company after it: it was going to be called Aspra. \n \nI started working on the application builder, Dan worked on network infrastructure, and the two \nundergrads worked on the first two services (images and phone calls). But about halfway through the \nsummer I realized I really didn't want to run a company — especially not a big one, which it was looking \nlike this would have to be. I'd only started Viaweb because I needed the money. Now that I didn't need \nmoney anymore, why was I doing this? If this vision had to be realized as a company, then screw the \nvision. I'd build a subset that could be done as an open source project. \n \nMuch to my surprise, the time I spent working on this stuff was not wasted after all. After we started Y \nCombinator, I would often encounter startups working on parts of this new architecture, and it was very \nuseful to have spent so much time thinking about it and even trying to write some of it. \n \nThe subset I would build as an open source project was the new Lisp, whose parentheses I now wouldn't \neven have to hide. A lot of Lisp hackers dream of building a new Lisp, partly because one of the \ndistinctive features of the language is that it has dialects, and partly, I think, because we have in our \nminds a Platonic form of Lisp that all existing dialects fall short of. I certainly did. So at the end of the \nsummer Dan and I switched to working on this new dialect of Lisp, which I called Arc, in a house I bought \nin Cambridge. \n \nThe following spring, lightning struck. I was invited to give a talk at a Lisp conference, so I gave one \nabout how we'd used Lisp at Viaweb. Afterward I put a postscript file of this talk online, on",
    "about how we'd used Lisp at Viaweb. Afterward I put a postscript file of this talk online, on \npaulgraham.com, which I'd created years before using Viaweb but had never used for anything. In one \nday it got 30,000 page views. What on earth had happened? The referring urls showed that someone \nhad posted it on Slashdot. [10] \n \nWow, I thought, there's an audience. If I write something and put it on the web, anyone can read it. That \nmay seem obvious now, but it was surprising then. In the print era there was a narrow channel to \nreaders, guarded by fierce monsters known as editors. The only way to get an audience for anything you \nwrote was to get it published as a book, or in a newspaper or magazine. Now anyone could publish \nanything. \n \nThis had been possible in principle since 1993, but not many people had realized it yet. I had been \nintimately involved with building the infrastructure of the web for most of that time, and a writer as \nwell, and it had taken me 8 years to realize it. Even then it took me several years to understand the \nimplications. It meant there would be a whole new generation of essays. [11]",
    "In the print era, the channel for publishing essays had been vanishingly small. Except for a few officially \nanointed thinkers who went to the right parties in New York, the only people allowed to publish essays \nwere specialists writing about their specialties. There were so many essays that had never been written, \nbecause there had been no way to publish them. Now they could be, and I was going to write them. [12] \n \nI've worked on several different things, but to the extent there was a turning point where I figured out \nwhat to work on, it was when I started publishing essays online. From then on I knew that whatever else \nI did, I'd always write essays too. \n \nI knew that online essays would be a marginal medium at first. Socially they'd seem more like rants \nposted by nutjobs on their GeoCities sites than the genteel and beautifully typeset compositions \npublished in The New Yorker. But by this point I knew enough to find that encouraging instead of \ndiscouraging. \n \nOne of the most conspicuous patterns I've noticed in my life is how well it has worked, for me at least, \nto work on things that weren't prestigious. Still life has always been the least prestigious form of \npainting. Viaweb and Y Combinator both seemed lame when we started them. I still get the glassy eye \nfrom strangers when they ask what I'm writing, and I explain that it's an essay I'm going to publish on my \nweb site. Even Lisp, though prestigious intellectually in something like the way Latin is, also seems about \nas hip. \n \nIt's not that unprestigious types of work are good per se. But when you find yourself drawn to some kind \nof work despite its current lack of prestige, it's a sign both that there's something real to be discovered \nthere, and that you have the right kind of motives. Impure motives are a big danger for the ambitious. If \nanything is going to lead you astray, it will be the desire to impress people. So while working on things",
    "that aren't prestigious doesn't guarantee you're on the right track, it at least guarantees you're not on \nthe most common type of wrong one. \n \nOver the next several years I wrote lots of essays about all kinds of different topics. O'Reilly reprinted a \ncollection of them as a book, called Hackers & Painters after one of the essays in it. I also worked on \nspam filters, and did some more painting. I used to have dinners for a group of friends every thursday \nnight, which taught me how to cook for groups. And I bought another building in Cambridge, a former \ncandy factory (and later, twas said, porn studio), to use as an office. \n \nOne night in October 2003 there was a big party at my house. It was a clever idea of my friend Maria \nDaniels, who was one of the thursday diners. Three separate hosts would all invite their friends to one",
    "party. So for every guest, two thirds of the other guests would be people they didn't know but would \nprobably like. One of the guests was someone I didn't know but would turn out to like a lot: a woman \ncalled Jessica Livingston. A couple days later I asked her out. \n \nJessica was in charge of marketing at a Boston investment bank. This bank thought it understood \nstartups, but over the next year, as she met friends of mine from the startup world, she was surprised \nhow different reality was. And how colorful their stories were. So she decided to compile a book of \ninterviews with startup founders. \n \nWhen the bank had financial problems and she had to fire half her staff, she started looking for a new \njob. In early 2005 she interviewed for a marketing job at a Boston VC firm. It took them weeks to make \nup their minds, and during this time I started telling her about all the things that needed to be fixed \nabout venture capital. They should make a larger number of smaller investments instead of a handful of \ngiant ones, they should be funding younger, more technical founders instead of MBAs, they should let \nthe founders remain as CEO, and so on. \n \nOne of my tricks for writing essays had always been to give talks. The prospect of having to stand up in \nfront of a group of people and tell them something that won't waste their time is a great spur to the \nimagination. When the Harvard Computer Society, the undergrad computer club, asked me to give a \ntalk, I decided I would tell them how to start a startup. Maybe they'd be able to avoid the worst of the \nmistakes we'd made. \n \nSo I gave this talk, in the course of which I told them that the best sources of seed funding were \nsuccessful startup founders, because then they'd be sources of advice too. Whereupon it seemed they \nwere all looking expectantly at me. Horrified at the prospect of having my inbox flooded by business",
    "plans (if I'd only known), I blurted out \"But not me!\" and went on with the talk. But afterward it \noccurred to me that I should really stop procrastinating about angel investing. I'd been meaning to since \nYahoo bought us, and now it was 7 years later and I still hadn't done one angel investment. \n \nMeanwhile I had been scheming with Robert and Trevor about projects we could work on together. I \nmissed working with them, and it seemed like there had to be something we could collaborate on. \n \nAs Jessica and I were walking home from dinner on March 11, at the corner of Garden and Walker \nstreets, these three threads converged. Screw the VCs who were taking so long to make up their minds. \nWe'd start our own investment firm and actually implement the ideas we'd been talking about. I'd fund \nit, and Jessica could quit her job and work for it, and we'd get Robert and Trevor as partners too. [13]",
    "Once again, ignorance worked in our favor. We had no idea how to be angel investors, and in Boston in \n2005 there were no Ron Conways to learn from. So we just made what seemed like the obvious choices, \nand some of the things we did turned out to be novel. \n \nThere are multiple components to Y Combinator, and we didn't figure them all out at once. The part we \ngot first was to be an angel firm. In those days, those two words didn't go together. There were VC \nfirms, which were organized companies with people whose job it was to make investments, but they \nonly did big, million dollar investments. And there were angels, who did smaller investments, but these \nwere individuals who were usually focused on other things and made investments on the side. And \nneither of them helped founders enough in the beginning. We knew how helpless founders were in \nsome respects, because we remembered how helpless we'd been. For example, one thing Julian had \ndone for us that seemed to us like magic was to get us set up as a company. We were fine writing fairly \ndifficult software, but actually getting incorporated, with bylaws and stock and all that stuff, how on \nearth did you do that? Our plan was not only to make seed investments, but to do for startups \neverything Julian had done for us. \n \nYC was not organized as a fund. It was cheap enough to run that we funded it with our own money. That \nwent right by 99% of readers, but professional investors are thinking \"Wow, that means they got all the \nreturns.\" But once again, this was not due to any particular insight on our part. We didn't know how VC \nfirms were organized. It never occurred to us to try to raise a fund, and if it had, we wouldn't have \nknown where to start. [14] \n \nThe most distinctive thing about YC is the batch model: to fund a bunch of startups all at once, twice a \nyear, and then to spend three months focusing intensively on trying to help them. That part we",
    "year, and then to spend three months focusing intensively on trying to help them. That part we \ndiscovered by accident, not merely implicitly but explicitly due to our ignorance about investing. We \nneeded to get experience as investors. What better way, we thought, than to fund a whole bunch of \nstartups at once? We knew undergrads got temporary jobs at tech companies during the summer. Why \nnot organize a summer program where they'd start startups instead? We wouldn't feel guilty for being \nin a sense fake investors, because they would in a similar sense be fake founders. So while we probably \nwouldn't make much money out of it, we'd at least get to practice being investors on them, and they for \ntheir part would probably have a more interesting summer than they would working at Microsoft. \n \nWe'd use the building I owned in Cambridge as our headquarters. We'd all have dinner there once a \nweek — on tuesdays, since I was already cooking for the thursday diners on thursdays — and after \ndinner we'd bring in experts on startups to give talks. \n \nWe knew undergrads were deciding then about summer jobs, so in a matter of days we cooked up \nsomething we called the Summer Founders Program, and I posted an announcement on my site, inviting \nundergrads to apply. I had never imagined that writing essays would be a way to get \"deal flow,\" as",
    "investors call it, but it turned out to be the perfect source. [15] We got 225 applications for the Summer \nFounders Program, and we were surprised to find that a lot of them were from people who'd already \ngraduated, or were about to that spring. Already this SFP thing was starting to feel more serious than \nwe'd intended. \n \nWe invited about 20 of the 225 groups to interview in person, and from those we picked 8 to fund. They \nwere an impressive group. That first batch included reddit, Justin Kan and Emmett Shear, who went on \nto found Twitch, Aaron Swartz, who had already helped write the RSS spec and would a few years later \nbecome a martyr for open access, and Sam Altman, who would later become the second president of \nYC. I don't think it was entirely luck that the first batch was so good. You had to be pretty bold to sign up \nfor a weird thing like the Summer Founders Program instead of a summer job at a legit place like \nMicrosoft or Goldman Sachs. \n \nThe deal for startups was based on a combination of the deal we did with Julian ($10k for 10%) and what \nRobert said MIT grad students got for the summer ($6k). We invested $6k per founder, which in the \ntypical two-founder case was $12k, in return for 6%. That had to be fair, because it was twice as good as \nthe deal we ourselves had taken. Plus that first summer, which was really hot, Jessica brought the \nfounders free air conditioners. [16] \n \nFairly quickly I realized that we had stumbled upon the way to scale startup funding. Funding startups in \nbatches was more convenient for us, because it meant we could do things for a lot of startups at once, \nbut being part of a batch was better for the startups too. It solved one of the biggest problems faced by \nfounders: the isolation. Now you not only had colleagues, but colleagues who understood the problems \nyou were facing and could tell you how they were solving them.",
    "you were facing and could tell you how they were solving them. \n \nAs YC grew, we started to notice other advantages of scale. The alumni became a tight community, \ndedicated to helping one another, and especially the current batch, whose shoes they remembered \nbeing in. We also noticed that the startups were becoming one another's customers. We used to refer \njokingly to the \"YC GDP,\" but as YC grows this becomes less and less of a joke. Now lots of startups get \ntheir initial set of customers almost entirely from among their batchmates. \n \nI had not originally intended YC to be a full-time job. I was going to do three things: hack, write essays, \nand work on YC. As YC grew, and I grew more excited about it, it started to take up a lot more than a \nthird of my attention. But for the first few years I was still able to work on other things. \n \nIn the summer of 2006, Robert and I started working on a new version of Arc. This one was reasonably \nfast, because it was compiled into Scheme. To test this new Arc, I wrote Hacker News in it. It was \noriginally meant to be a news aggregator for startup founders and was called Startup News, but after a",
    "few months I got tired of reading about nothing but startups. Plus it wasn't startup founders we wanted \nto reach. It was future startup founders. So I changed the name to Hacker News and the topic to \nwhatever engaged one's intellectual curiosity. \n \nHN was no doubt good for YC, but it was also by far the biggest source of stress for me. If all I'd had to \ndo was select and help founders, life would have been so easy. And that implies that HN was a mistake. \nSurely the biggest source of stress in one's work should at least be something close to the core of the \nwork. Whereas I was like someone who was in pain while running a marathon not from the exertion of \nrunning, but because I had a blister from an ill-fitting shoe. When I was dealing with some urgent \nproblem during YC, there was about a 60% chance it had to do with HN, and a 40% chance it had do with \neverything else combined. [17] \n \nAs well as HN, I wrote all of YC's internal software in Arc. But while I continued to work a good deal in \nArc, I gradually stopped working on Arc, partly because I didn't have time to, and partly because it was a \nlot less attractive to mess around with the language now that we had all this infrastructure depending \non it. So now my three projects were reduced to two: writing essays and working on YC. \n \nYC was different from other kinds of work I've done. Instead of deciding for myself what to work on, the \nproblems came to me. Every 6 months there was a new batch of startups, and their problems, whatever \nthey were, became our problems. It was very engaging work, because their problems were quite varied, \nand the good founders were very effective. If you were trying to learn the most you could about \nstartups in the shortest possible time, you couldn't have picked a better way to do it. \n \nThere were parts of the job I didn't like. Disputes between cofounders, figuring out when people were",
    "lying to us, fighting with people who maltreated the startups, and so on. But I worked hard even at the \nparts I didn't like. I was haunted by something Kevin Hale once said about companies: \"No one works \nharder than the boss.\" He meant it both descriptively and prescriptively, and it was the second part that \nscared me. I wanted YC to be good, so if how hard I worked set the upper bound on how hard everyone \nelse worked, I'd better work very hard. \n \nOne day in 2010, when he was visiting California for interviews, Robert Morris did something \nastonishing: he offered me unsolicited advice. I can only remember him doing that once before. One day \nat Viaweb, when I was bent over double from a kidney stone, he suggested that it would be a good idea \nfor him to take me to the hospital. That was what it took for Rtm to offer unsolicited advice. So I \nremember his exact words very clearly. \"You know,\" he said, \"you should make sure Y Combinator isn't \nthe last cool thing you do.\"",
    "At the time I didn't understand what he meant, but gradually it dawned on me that he was saying I \nshould quit. This seemed strange advice, because YC was doing great. But if there was one thing rarer \nthan Rtm offering advice, it was Rtm being wrong. So this set me thinking. It was true that on my current \ntrajectory, YC would be the last thing I did, because it was only taking up more of my attention. It had \nalready eaten Arc, and was in the process of eating essays too. Either YC was my life's work or I'd have to \nleave eventually. And it wasn't, so I would. \n \nIn the summer of 2012 my mother had a stroke, and the cause turned out to be a blood clot caused by \ncolon cancer. The stroke destroyed her balance, and she was put in a nursing home, but she really \nwanted to get out of it and back to her house, and my sister and I were determined to help her do it. I \nused to fly up to Oregon to visit her regularly, and I had a lot of time to think on those flights. On one of \nthem I realized I was ready to hand YC over to someone else. \n \nI asked Jessica if she wanted to be president, but she didn't, so we decided we'd try to recruit Sam \nAltman. We talked to Robert and Trevor and we agreed to make it a complete changing of the guard. Up \ntill that point YC had been controlled by the original LLC we four had started. But we wanted YC to last \nfor a long time, and to do that it couldn't be controlled by the founders. So if Sam said yes, we'd let him \nreorganize YC. Robert and I would retire, and Jessica and Trevor would become ordinary partners. \n \nWhen we asked Sam if he wanted to be president of YC, initially he said no. He wanted to start a startup \nto make nuclear reactors. But I kept at it, and in October 2013 he finally agreed. We decided he'd take \nover starting with the winter 2014 batch. For the rest of 2013 I left running YC more and more to Sam, \npartly so he could learn the job, and partly because I was focused on my mother, whose cancer had \nreturned.",
    "returned. \n \nShe died on January 15, 2014. We knew this was coming, but it was still hard when it did. \n \nI kept working on YC till March, to help get that batch of startups through Demo Day, then I checked out \npretty completely. (I still talk to alumni and to new startups working on things I'm interested in, but that \nonly takes a few hours a week.) \n \nWhat should I do next? Rtm's advice hadn't included anything about that. I wanted to do something \ncompletely different, so I decided I'd paint. I wanted to see how good I could get if I really focused on it. \nSo the day after I stopped working on YC, I started painting. I was rusty and it took a while to get back \ninto shape, but it was at least completely engaging. [18]",
    "I spent most of the rest of 2014 painting. I'd never been able to work so uninterruptedly before, and I \ngot to be better than I had been. Not good enough, but better. Then in November, right in the middle of \na painting, I ran out of steam. Up till that point I'd always been curious to see how the painting I was \nworking on would turn out, but suddenly finishing this one seemed like a chore. So I stopped working on \nit and cleaned my brushes and haven't painted since. So far anyway. \n \nI realize that sounds rather wimpy. But attention is a zero sum game. If you can choose what to work on, \nand you choose a project that's not the best one (or at least a good one) for you, then it's getting in the \nway of another project that is. And at 50 there was some opportunity cost to screwing around. \n \nI started writing essays again, and wrote a bunch of new ones over the next few months. I even wrote a \ncouple that weren't about startups. Then in March 2015 I started working on Lisp again. \n \nThe distinctive thing about Lisp is that its core is a language defined by writing an interpreter in itself. It \nwasn't originally intended as a programming language in the ordinary sense. It was meant to be a formal \nmodel of computation, an alternative to the Turing machine. If you want to write an interpreter for a \nlanguage in itself, what's the minimum set of predefined operators you need? The Lisp that John \nMcCarthy invented, or more accurately discovered, is an answer to that question. [19] \n \nMcCarthy didn't realize this Lisp could even be used to program computers till his grad student Steve \nRussell suggested it. Russell translated McCarthy's interpreter into IBM 704 machine language, and from \nthat point Lisp started also to be a programming language in the ordinary sense. But its origins as a \nmodel of computation gave it a power and elegance that other languages couldn't match. It was this \nthat attracted me in college, though I didn't understand why at the time.",
    "that attracted me in college, though I didn't understand why at the time. \n \nMcCarthy's 1960 Lisp did nothing more than interpret Lisp expressions. It was missing a lot of things \nyou'd want in a programming language. So these had to be added, and when they were, they weren't \ndefined using McCarthy's original axiomatic approach. That wouldn't have been feasible at the time. \nMcCarthy tested his interpreter by hand-simulating the execution of programs. But it was already \ngetting close to the limit of interpreters you could test that way — indeed, there was a bug in it that \nMcCarthy had overlooked. To test a more complicated interpreter, you'd have had to run it, and \ncomputers then weren't powerful enough. \n \nNow they are, though. Now you could continue using McCarthy's axiomatic approach till you'd defined a \ncomplete programming language. And as long as every change you made to McCarthy's Lisp was a \ndiscoveredness-preserving transformation, you could, in principle, end up with a complete language that \nhad this quality. Harder to do than to talk about, of course, but if it was possible in principle, why not",
    "try? So I decided to take a shot at it. It took 4 years, from March 26, 2015 to October 12, 2019. It was \nfortunate that I had a precisely defined goal, or it would have been hard to keep at it for so long. \n \nI wrote this new Lisp, called Bel, in itself in Arc. That may sound like a contradiction, but it's an indication \nof the sort of trickery I had to engage in to make this work. By means of an egregious collection of hacks \nI managed to make something close enough to an interpreter written in itself that could actually run. \nNot fast, but fast enough to test. \n \nI had to ban myself from writing essays during most of this time, or I'd never have finished. In late 2015 I \nspent 3 months writing essays, and when I went back to working on Bel I could barely understand the \ncode. Not so much because it was badly written as because the problem is so convoluted. When you're \nworking on an interpreter written in itself, it's hard to keep track of what's happening at what level, and \nerrors can be practically encrypted by the time you get them. \n \nSo I said no more essays till Bel was done. But I told few people about Bel while I was working on it. So \nfor years it must have seemed that I was doing nothing, when in fact I was working harder than I'd ever \nworked on anything. Occasionally after wrestling for hours with some gruesome bug I'd check Twitter or \nHN and see someone asking \"Does Paul Graham still code?\" \n \nWorking on Bel was hard but satisfying. I worked on it so intensively that at any given time I had a \ndecent chunk of the code in my head and could write more there. I remember taking the boys to the \ncoast on a sunny day in 2015 and figuring out how to deal with some problem involving continuations \nwhile I watched them play in the tide pools. It felt like I was doing life right. I remember that because I \nwas slightly dismayed at how novel it felt. The good news is that I had more moments like this over the \nnext few years.",
    "next few years. \n \nIn the summer of 2016 we moved to England. We wanted our kids to see what it was like living in \nanother country, and since I was a British citizen by birth, that seemed the obvious choice. We only \nmeant to stay for a year, but we liked it so much that we still live there. So most of Bel was written in \nEngland. \n \nIn the fall of 2019, Bel was finally finished. Like McCarthy's original Lisp, it's a spec rather than an \nimplementation, although like McCarthy's Lisp it's a spec expressed as code. \n \nNow that I could write essays again, I wrote a bunch about topics I'd had stacked up. I kept writing \nessays through 2020, but I also started to think about other things I could work on. How should I choose \nwhat to do? Well, how had I chosen what to work on in the past? I wrote an essay for myself to answer",
    "that question, and I was surprised how long and messy the answer turned out to be. If this surprised me, \nwho'd lived it, then I thought perhaps it would be interesting to other people, and encouraging to those \nwith similarly messy lives. So I wrote a more detailed version for others to read, and this is the last \nsentence of it. \n \n \n \n \n \n \n \n \n \nNotes \n \n[1] My experience skipped a step in the evolution of computers: time-sharing machines with interactive \nOSes. I went straight from batch processing to microcomputers, which made microcomputers seem all \nthe more exciting. \n \n[2] Italian words for abstract concepts can nearly always be predicted from their English cognates \n(except for occasional traps like polluzione). It's the everyday words that differ. So if you string together \na lot of abstract concepts with a few simple verbs, you can make a little Italian go a long way. \n \n[3] I lived at Piazza San Felice 4, so my walk to the Accademia went straight down the spine of old \nFlorence: past the Pitti, across the bridge, past Orsanmichele, between the Duomo and the Baptistery, \nand then up Via Ricasoli to Piazza San Marco. I saw Florence at street level in every possible condition, \nfrom empty dark winter evenings to sweltering summer days when the streets were packed with \ntourists. \n \n[4] You can of course paint people like still lives if you want to, and they're willing. That sort of portrait is \narguably the apex of still life painting, though the long sitting does tend to produce pained expressions \nin the sitters.",
    "[5] Interleaf was one of many companies that had smart people and built impressive technology, and yet \ngot crushed by Moore's Law. In the 1990s the exponential growth in the power of commodity (i.e. Intel) \nprocessors rolled up high-end, special-purpose hardware and software companies like a bulldozer. \n \n[6] The signature style seekers at RISD weren't specifically mercenary. In the art world, money and \ncoolness are tightly coupled. Anything expensive comes to be seen as cool, and anything seen as cool \nwill soon become equally expensive. \n \n[7] Technically the apartment wasn't rent-controlled but rent-stabilized, but this is a refinement only \nNew Yorkers would know or care about. The point is that it was really cheap, less than half market price. \n \n[8] Most software you can launch as soon as it's done. But when the software is an online store builder \nand you're hosting the stores, if you don't have any users yet, that fact will be painfully obvious. So \nbefore we could launch publicly we had to launch privately, in the sense of recruiting an initial set of \nusers and making sure they had decent-looking stores. \n \n[9] We'd had a code editor in Viaweb for users to define their own page styles. They didn't know it, but \nthey were editing Lisp expressions underneath. But this wasn't an app editor, because the code ran \nwhen the merchants' sites were generated, not when shoppers visited them. \n \n[10] This was the first instance of what is now a familiar experience, and so was what happened next, \nwhen I read the comments and found they were full of angry people. How could I claim that Lisp was \nbetter than other languages? Weren't they all Turing complete? People who see the responses to essays \nI write sometimes tell me how sorry they feel for me, but I'm not exaggerating when I reply that it has \nalways been like this, since the very beginning. It comes with the territory. An essay must tell readers",
    "things they don't already know, and some people dislike being told such things. \n \n[11] People put plenty of stuff on the internet in the 90s of course, but putting something online is not \nthe same as publishing it online. Publishing online means you treat the online version as the (or at least \na) primary version. \n \n[12] There is a general lesson here that our experience with Y Combinator also teaches: Customs \ncontinue to constrain you long after the restrictions that caused them have disappeared. Customary VC \npractice had once, like the customs about publishing essays, been based on real constraints. Startups \nhad once been much more expensive to start, and proportionally rare. Now they could be cheap and \ncommon, but the VCs' customs still reflected the old world, just as customs about writing essays still \nreflected the constraints of the print era.",
    "Which in turn implies that people who are independent-minded (i.e. less influenced by custom) will have \nan advantage in fields affected by rapid change (where customs are more likely to be obsolete). \n \nHere's an interesting point, though: you can't always predict which fields will be affected by rapid \nchange. Obviously software and venture capital will be, but who would have predicted that essay writing \nwould be? \n \n[13] Y Combinator was not the original name. At first we were called Cambridge Seed. But we didn't \nwant a regional name, in case someone copied us in Silicon Valley, so we renamed ourselves after one of \nthe coolest tricks in the lambda calculus, the Y combinator. \n \nI picked orange as our color partly because it's the warmest, and partly because no VC used it. In 2005 \nall the VCs used staid colors like maroon, navy blue, and forest green, because they were trying to \nappeal to LPs, not founders. The YC logo itself is an inside joke: the Viaweb logo had been a white V on a \nred circle, so I made the YC logo a white Y on an orange square. \n \n[14] YC did become a fund for a couple years starting in 2009, because it was getting so big I could no \nlonger afford to fund it personally. But after Heroku got bought we had enough money to go back to \nbeing self-funded. \n \n[15] I've never liked the term \"deal flow,\" because it implies that the number of new startups at any \ngiven time is fixed. This is not only false, but it's the purpose of YC to falsify it, by causing startups to be \nfounded that would not otherwise have existed. \n \n[16] She reports that they were all different shapes and sizes, because there was a run on air \nconditioners and she had to get whatever she could, but that they were all heavier than she could carry \nnow. \n \n[17] Another problem with HN was a bizarre edge case that occurs when you both write essays and run \na forum. When you run a forum, you're assumed to see if not every conversation, at least every",
    "a forum. When you run a forum, you're assumed to see if not every conversation, at least every \nconversation involving you. And when you write essays, people post highly imaginative \nmisinterpretations of them on forums. Individually these two phenomena are tedious but bearable, but \nthe combination is disastrous. You actually have to respond to the misinterpretations, because the \nassumption that you're present in the conversation means that not responding to any sufficiently",
    "upvoted misinterpretation reads as a tacit admission that it's correct. But that in turn encourages more; \nanyone who wants to pick a fight with you senses that now is their chance. \n \n[18] The worst thing about leaving YC was not working with Jessica anymore. We'd been working on YC \nalmost the whole time we'd known each other, and we'd neither tried nor wanted to separate it from \nour personal lives, so leaving was like pulling up a deeply rooted tree. \n \n[19] One way to get more precise about the concept of invented vs discovered is to talk about space \naliens. Any sufficiently advanced alien civilization would certainly know about the Pythagorean theorem, \nfor example. I believe, though with less certainty, that they would also know about the Lisp in \nMcCarthy's 1960 paper. \n \nBut if so there's no reason to suppose that this is the limit of the language that might be known to them. \nPresumably aliens need numbers and errors and I/O too. So it seems likely there exists at least one path \nout of McCarthy's Lisp along which discoveredness is preserved. \n \n \n \nThanks to Trevor Blackwell, John Collison, Patrick Collison, Daniel Gackle, Ralph Hazell, Jessica \nLivingston, Robert Morris, and Harj Taggar for reading drafts of this."
]


async def process_steps(app, split_docs):
    async for step in app.astream(
        {"contents": [doc for doc in split_docs]},
        {"recursion_limit": 10},
    ):
        print(step)


if __name__ == "__main__":
    # Call the async function
    import asyncio
    asyncio.run(process_steps(app, split_docs))